### ISSUE TITLE
Better title

### ISSUE THREAD

**Issue by bandaloo** [bandaloo/afterlight-caves#56]
We've gone a long time with this working title.

**Comment by jojonium** [comment]
Maybe "Caves of [something]," and we could try to incorporate "proc" into some kind of fantasy/sci-fi sounding place name

**Comment by jojonium** [comment]
We should also acquire a domain name based on the title at some point

**Comment by bandaloo** [comment]
> Maybe "Caves of [something]," and we could try to incorporate "proc"
Caves of Prok
