### ISSUE TITLE
Score display behavior

### ISSUE THREAD

**Issue by jojonium** [bandaloo/afterlight-caves#70]
New scores should stack up under the total score, and linger there for a second before adding to the total score so you can see how much everything is worth. Also the speed at which score drains into the total should increase over time.

**Comment by bandaloo** [comment]
Should the speed increase over time or decrease exponentially? I would rather see it look something like

`12345` at 100 ms after start of draining
`6789` at 200 ms
`101` at 300 ms
`12` at 400 ms
`1` at 500 ms

Sort of have the rate asymptotically approach 0 plus some scalar

**Comment by jojonium** [comment]
Resolved by #78
