### ISSUE TITLE
JavaFX Webview Optimization

### ISSUE THREAD

**Issue by gusteran** [bandaloo/afterlight-caves#81]
The javascript does not run in a JavaFX Webview pane. I would enjoy if you optimized your otherwise wonderful game for my favorite browser, JavaFX Webview.

**Comment by gusteran** [comment]
It doesn't work for netview either, the default xfce browser

**Comment by jojonium** [comment]
I have no way of testing this, but I added a script that should build a more compatible version of the game in the `babel` branch. Try this:

```
$ git checkout babel
$ npm install
$ npm run start-compat
```

And see if it works in whatever browser you want by navigating to http://localhost:4000. You can then run `npm run build` to build the compatibility version of the game in the `dist` directory.

**Comment by bandaloo** [comment]
Similarly, I just tried to play the game on the Wii Internet Channel and it wouldn't work. It's a shame the devs are ignoring this group of users.

**Comment by jojonium** [comment]
The babel functionality got merged into master (see #98), so the production version should be compatible with most reasonable browsers. As such, I'm closing this issue
